### ISSUE TITLE
Unable to find a suitable output format for 'xxx.mp4'

### ISSUE THREAD

**Issue by kolyneh** [baka3k/IjkPlayerRecorder#4]
Hi, I'm using this lib to record a MJPEG stream video , but it logs: Unable to find a suitable output format for 'xxx.mp4'.
How to get it work?

**Comment by baka3k** [comment]
@kolyneh please make sure that:
1. your path is correct
2. your application has 'external storage permission'

**Comment by kolyneh** [comment]
Hi, it looks like that the `.so` library I build is different from yours.

Now I'm trying your `RTSPRecorder` project,
I just change `mVideoPath` to a MJPGE stream ` "http://webcam1.vilhelmina.se/mjpg/video.mjpg?resolution=640x480"`.
When starting record it crash:
![1636519337](https://user-images.githubusercontent.com/13062910/141051075-670efe82-72aa-4028-a21f-3e4d5fab7e66.png)

**Comment by baka3k** [comment]
Oh, I see...
Root the problem is when we compiled so file, we are missing config for MJPEG, 
So, it's work good with H.264 but not work with MJPEG
If you want support MJPEG - please compiler ffmpeg to open to support MJPEG(https://github.com/baka3k/IjkPlayerRecorder/tree/master/config) 
Then compile .so again. 
Have fun 👍

**Comment by kolyneh** [comment]
Thanks, but my build is configurated as `module-default.sh`, MJPEG it's already supported:
It can play MJPEG stream but not recording, just logs `Unable to find a suitable output format for 'xxx.mp4'.`

For your build when playing MJPEG stream just a corner is shown other area is green, as you said it's the MJPEG support thing, and thus the recording wont work.

**Comment by kolyneh** [comment]
Another thing is your build works for RTSP both playing and recording , but my build works for MJPEG/RTSP only on playing.
I'm trying to use the `module-lite.sh` config and add MJPEG/RTSP support to see if it will work.

**Comment by kolyneh** [comment]
Hi @baka3k 
After trying several times using `module-lite.sh` to add MJPEG support, now it's working on playing MJPEG stream.
But for recording, it logs out of range:
```
W/IJKMEDIA: cjz ijkmp_stop_recording
E/IJKMEDIA: don't need stopRecord
W/IJKMEDIA: cjz ijkmp_start_recording --- 
I/IJKMEDIA: cjz ijkmp_start_recording_l filePath /storage/emulated/0/Download/b.mp4
I/IJKMEDIA: Output #0, mp4, to '/storage/emulated/0/Download/b.mp4':
I/IJKMEDIA:     Stream #0:0
I/IJKMEDIA: : Unknown: none
W/IJKMEDIA: Using AVStream.codec to pass codec parameters to muxers is deprecated, use AVStream.codecpar instead.
E/IJKMEDIA: av_read_frame error: unknown
E/IJKMEDIA: Application provided duration: 691752902762830186 / timestamp: 691752902763179386 is out of range for mov/mp4 format
W/IJKMEDIA: pts has no value
I/IJKMEDIA: ffp_toggle_buffering: error: -104
E/IJKMEDIA: av_read_frame error: unknown
D/IJKMEDIA: FFP_MSG_ERROR: 0
E/tv.danmaku.ijk.media.player.IjkMediaPlayer: Error (-10000,0)
D/IjkVideoView: Error: -10000,0
E/IJKMEDIA: Application provided invalid, non monotonically increasing dts to muxer in stream 0: 691752902763179386 >= 691752902763179386
E/IJKMEDIA: Error muxing packet
I/IJKMEDIA: ffp_toggle_buffering: eof
```
What's going on like this?

**Comment by kolyneh** [comment]
Finally added `jpeg` support to get it work!
Thanks @baka3k .
